# Generated by Django 4.2.11 on 2025-06-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bkash_transaction_id',
            new_name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash on Delivery'), (2, 'Bank Transfer'), (3, 'PayPal'), (4, 'SSLCommerz'), (5, 'Stripe')], default=1),
        ),
    ]
